there is an error in the preview of app:
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):
Error:   x Expected a semicolon

    ,-[/home/user/studio/src/hooks/useQRCodeScanner.ts:93:1]

 90 |         //   }

 91 |         // }, 5000);

 92 |

 93 |       } else {

    :         ^^^^

 94 |         setError("Video element is not available.");

 95 |         stopScan();

 96 |       }

    `----

Caused by:

    Syntax Error

    at processResult (file:///home/user/studio/node_modules/next/dist/compiled/webpack/bundle5.js:29:407111)

    at <unknown> (file:///home/user/studio/node_modules/next/dist/compiled/webpack/bundle5.js:29:408906)

    at <unknown> (file:///home/user/studio/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8645)

    at <unknown> (file:///home/user/studio/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5019)

    at r.callback (file:///home/user/studio/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)